name = "iss-tracker-api"
main = "src/server/index.ts"
compatibility_date = "2024-01-01"

[vars]
# Add your environment variables here or use wrangler secret put

# Example for Redis connection
# REDIS_HOST = "your-redis-host"
# REDIS_PORT = "6379"

# For secrets (recommended for passwords):
# Run: wrangler secret put REDIS_PASSWORD